# approval-test.yml
#   承認のための action
#   terraform-apply-test.yml から呼び出され、承認が完了すると処理が terraform-apply-test.yml に戻る

name: approval for terraform apply

on:
  workflow_dispatch:
    inputs:
      plan_only:
        description: 'run only terraform plan'
        type: choice
        options:
          - yes
          - no
        required: true

env:
  TERRAFORM_VERSION: 1.3.6  # .terraform-version と同じ
  AWS_REGION: ap-northeast-1
  TZ: 'Asia/Tokyo'

permissions:
  id-token: write
  contents: read

jobs:
  approval-test:
    permissions: write-all
    environment:
      name: ${{ vars.ENVIRONMENT_STAGE }}
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Set current datetime as env variable
        if: github.event.inputs.plan_only == 'no'
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
          echo "boolean=${{ github.event.inputs.plan_only }}" >> $GITHUB_ENV
          echo "environment_stage=${{ vars.ENVIRONMENT_STAGE }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # 開発環境は今のところ自分のIAMのアクセスキーを利用しているため
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install AWS CLI v2 for local env
        if: ${{ env.ACT }}   # ローカル開発環境（act）のみ実施する
        run:  |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

      - id: create-change-request
        run: |
          echo "execution_id=$(aws ssm start-change-request-execution \
              --change-request-name MyChangeRequest \
              --document-name AWS-HelloWorldChangeTemplate \
              --runbooks '[{"DocumentName": "AWS-HelloWorld","Parameters": {"AutomationAssumeRole": ["arn:aws:iam::413564730959:role/kakin-ssm-full-access-test"]}}]' \
              --parameters Approver="kakin-ssm-full-access-test",ApproverType="IamRole",ApproverSnsTopicArn="arn:aws:sns:ap-northeast-1:413564730959:kakin-approval-test" \
              --query "AutomationExecutionId" --output text)" >> $GITHUB_ENV

      - name: Check if change request approved
        run: |
          response="none"
          while [ "$response" != "CompletedWithSuccess" ]; \
          do \
            sleep 5; \
            response=$(aws ssm get-automation-execution --automation-execution-id ${{ env.execution_id }} \
                    --query "AutomationExecution.AutomationExecutionStatus" --output text); \
          done
