# approval-test.yml
#   承認のための action
#   terraform-apply-test.yml から呼び出され、承認が完了すると処理が terraform-apply-test.yml に戻る

name: approval for terraform apply

on:
  workflow_call:

env:
  TERRAFORM_VERSION: 1.3.6  # .terraform-version と同じ
  WORKING_DIRECTORY: ${{ github.event.inputs.target_terraform_directory }}
  AWS_REGION: ap-northeast-1
  TZ: 'Asia/Tokyo'

permissions:
  id-token: write
  contents: read

jobs:
  approval-test:
    permissions: write-all
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set current datetime as env variable
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
