# terraform-apply-test.yml
#   対象ブランチの対象ディレクトリで terraform plan を実行し、結果を artifact としてアップロードする
#   対象ブランチの pull request が open の場合、 pull request に plan 結果をコメントとして書き込む

name: terraform apply

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'target branch (ex. feature/KP-0000)'
        required: true
      target_terraform_directory:
        description: 'target terraform directory (ex. terraform/environments/dev)'
        required: true

env:
  TERRAFORM_VERSION: 1.3.6  # .terraform-version と同じ
  WORKING_DIRECTORY: ${{ github.event.inputs.target_terraform_directory }}
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    permissions: write-all
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # 開発環境は今のところ自分のIAMのアクセスキーを利用しているため
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Config Terraform plugin cache
        run: |
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
          mkdir --parents ~/.terraform.d/plugin-cache

      - name: Cache Terraform  # ローカル開発環境ではCacheは動作しない
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Download plan result
        uses: actions/download-artifact@v3
        with:
          name: terraform_plan

      - name: Display structure of downloaded files
        run: |
          ls -R
          cat terraform_plan.txt
